import logging
from io import BytesIO
from typing import Any

from mutagen.mp4 import MP4, MP4Cover
from PIL import Image
from PIL.Image import Image as PILImage
from yt_dlp.postprocessor.common import PostProcessor

LOGGER = logging.getLogger(__name__)


class MissingCoverError(Exception): ...


def load_album_art(mp4: MP4) -> PILImage:
    covers = mp4.tags.get("covr")
    if not covers:
        raise MissingCoverError(mp4.filename)
    if len(covers) > 1:
        raise NotImplementedError(f"expected one cover, got {len(covers)}")
    return Image.open(BytesIO(covers[0]))


def save_album_art(mp4: MP4, img: PILImage) -> None:
    buffer = BytesIO()
    img.save(buffer, format="JPEG")
    data = buffer.getvalue()
    mp4.tags["covr"] = [MP4Cover(data, imageformat=MP4Cover.FORMAT_JPEG)]
    mp4.save()


def crop_center_square(img: PILImage) -> PILImage:
    w, h = img.size
    side = min(w, h)
    left = (w - side) // 2
    top = (h - side) // 2
    right = left + side
    bottom = top + side
    return img.crop((left, top, right, bottom))


class YouTubeMusicSquareThumbnailPP(PostProcessor):
    def run(self, information: dict[str, Any]):
        if not information["description"].endswith("Auto-generated by YouTube."):
            return [], information
        mp4 = MP4(information["filepath"])
        img = load_album_art(mp4)
        img_cropped = crop_center_square(img)
        save_album_art(mp4, img_cropped)
        return [], information
